### ISSUE TITLE
Credentials is empty, generating...

### ISSUE THREAD

**Issue by p4uladam** [adekmaulana/aioaria2-mirror-bot#41]
I'm getting Credentials is empty, generating... in the bot

Here's the log file: https://pastebin.com/nE1hfceP

**Comment by adekmaulana** [comment]
> I'm getting Credentials is empty, generating... in the bot
> 
> Here's the log file: https://pastebin.com/nE1hfceP

It's should be fixed on new commits, you can pull or refork.
Thanks for the log!

**Comment by p4uladam** [comment]
Thanks, it's working now
