### ISSUE TITLE
banyak bug, need more improvement and more plug-in

### ISSUE THREAD

**Issue by tomyprs** [adekmaulana/aioaria2-mirror-bot#6]
ngebug kek owners nya

**Comment by adekmaulana** [comment]
> ngebug kek owners nya

Tele gw didelete sama Telegram atau lu iseng kali ya, gw baru engeh pas buka tele ga ada notif sama sekali

**Comment by tomyprs** [comment]
@adekmaulana Selain pintar bikin logic program, lu juga jago banget bikin logic berdrama :-D salut
